---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-code-cs0
  namespace: code
  labels:
    volume: pv-code-cs0
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/storage/local-storage/code-server/cs0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - srv01 # kubernetes node name
