--- 
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: pvc-code-cs0
  namespace: code
spec: 
  accessModes: 
  - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: pv-code-cs0