---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-freeipa
  namespace: freeipa
  labels:
    volume: pv-freeipa
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/storage/local-storage/freeipa
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - srv01 # kubernetes node name
