--- 
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: pvc-freeipa
  namespace: freeipa
spec: 
  accessModes: 
  - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: pv-freeipa