Vagrant.configure("2") do |config|
  #config.vm.provider "virtualbox" do |v|
  (1).each do |i|
    config.vm.define "master_#{i}" do |master|
      master.vm.box = "generic/ubuntu2204"
      master.vm.network "public_network", bridge: "wlp1s0", ip: "192.168.5.200"
    end
  end


  (1..5).each do |i|
    config.vm.define "worker_#{i}" do |worker|
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "public_network", bridge: "wlp1s0", ip: "192.168.5.20#{i}"
      #worker.vm.network "public_network", bridge: "wlp1s0", auto_config: false
      #worker.vm.provision "shell", path: "k8s_#{i}.sh"
    end
  end
end