---
version: "3"
services:
  app:
    image: nextcloud:latest
    restart: always
    networks:
      nextcloud-net:
        ipv4_address: 172.19.0.2
    expose:
      - "80"
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /opt/nextcloud/html:/var/www/html:rw
      - /opt/nextcloud/data:/srv/nextcloud/data:rw
    environment:
      - POSTGRES_HOST=192.168.5.211}
      - POSTGRES_DB=${POSTGRES_DB}                              # Banco de dados para o Nextcloud, poderá ser outro de sua preferência
      - POSTGRES_USER=${POSTGRES_USER}                          # Usuário do banco de dados Nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}                  # Senha para o usuário nextcloud_user
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}    # Defina a senha para o usuário administrador do Nextcloud
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}            # Defina o nome de usuário que será administrador do Nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}  # Defina um domínio
      - SKIP_DOMAIN_VALIDATION=true                             # Evita a validação de domínio
      - VIRTUAL_HOST=192.168.5.120                              # Defina com o IP do Host 
    secrets:
      - secrets-file
  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx
    restart: always
    networks:
      nextcloud-net:
        ipv4_address: 172.19.0.5
    ports:
      - 80:80
      - 443:443
    links:
      - app
    environment:
      - TLS_CERT=/etc/tls/server.crt
      - TLS_KEY=/etc/tls/server.key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/tls
secrets:
  secrets-file:
    file: ./secrets.txt
networks:
  nextcloud-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16