---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-server
  namespace: essentials
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/storage/local-storage/nfs-server
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - srv01
--- 
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: pvc-nfs-server
  namespace: essentials
spec: 
  accessModes: 
  - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi 