apiVersion: v1
kind: Secret
metadata:
  name: essentials-pgsql-secret
  namespace: essentials
  labels:
    app: postgres
type: Opaque
stringData:
  dbname: essentials 
  username: postgres
  password: Q2hhbmdlVGhpc1Bhc3N3b3JkCg== # This is a example, change this
